name: CD to Production

on:
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Validate deployment secrets
              run: |
                  if [ -z "${{ secrets.SSH_USERNAME }}" ]; then
                    echo "Error: SSH_USERNAME secret is not set."
                    exit 1
                  fi
